### ISSUE TITLE
Probably not the fault of the program but might be a common issue

### ISSUE THREAD

**Issue by DriverKit** [benrugg/AI-Render#104]
### Describe the bug

Hi,

Firstly thanks for creating this addon.  It is interesting to play around a create renders.  I have done a local installation partly to give me a setup challenge and also becuase I am unemployed and don't want to spend the money on rendering.

A few things I noticed.  I already had a version of python installed from the windows store.  This version of python took precedence over the 3.10.6 (?) version required to run the addon.  In the end I uninstalled the windows store python and this seemed to fix that issue.  But it took me a long to identify and resolve this.  Perhaps there is a way to make sure 3.10.6 version takes precedence even if other python versions are installed by creating a specific folder or venv for it to be installed in with a secific path?

I also found the xformers was not loading so followed the steps in the stable diffusion(?) git and reinstalled xformers and kept --xformers in the launching web ui arguments.  I would suggest making that process of reinstalling xformers and --xformers a default to add along with --api

When I use the addon I can complete one render and then I need to restart the program becuase the Cuda runs out of memory.   There are some mentions of similar issues on the git but maybe it is possible to address in the program as it maybe a common occurence?  I am running on an msi laptop with nvidia graphics card:

### To reproduce

render an image then try to render another image.  This may be due to my hardware setup?

### Error log

venv "C:\Users\Tom\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 5ab7f213bec2f816f9c5644becb32eb72c8ffb89
Installing requirements
Launching Web UI with arguments: --api --xformers
Loading weights [6ce0161689] from C:\Users\Tom\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Creating model from config: C:\Users\Tom\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0):
Model loaded in 3.4s (load weights from disk: 0.2s, create model: 0.4s, apply weights to model: 0.6s, apply half(): 0.6s, move model to device: 0.5s, load textual inversion embeddings: 1.0s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 9.6s (import torch: 1.5s, import gradio: 0.9s, import ldm: 0.6s, other imports: 0.8s, load scripts: 1.1s, load SD checkpoint: 3.7s, create ui: 0.6s, gradio launch: 0.1s, scripts app_started_callback: 0.1s).
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [01:43<00:00,  3.71s/it]
API error: POST: http://127.0.0.1:7860/sdapi/v1/img2img {'error': 'OutOfMemoryError', 'detail': '', 'body': '', 'errors': 'CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 4.00 GiB total capacity; 2.34 GiB already allocated; 0 bytes free; 2.49 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF'}
Traceback (most recent call last):
  File "C:\Users\Tom\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 94, in receive
    return self.receive_nowait()
  File "C:\Users\Tom\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Tom\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
    message = await recv_stream.receive()
  File "C:\Users\Tom\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Tom\stable-diffusion-webui\modules\api\api.py", line 144, in exception_handling
    return await call_next(request)
  File "C:\Users\Tom\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "C:\Users\Tom\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Tom\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\Users\Tom\stable-diffusion-webui\modules\api\api.py", line 109, in log_and_time
    res: Response = await call_next(req)
  File "C:\Users\Tom\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "C:\Users\Tom\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Tom\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "C:\Users\Tom\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "C:\Users\Tom\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\Tom\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\Tom\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\Tom\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Tom\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\Tom\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Tom\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\Tom\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\Tom\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\Tom\stable-diffusion-webui\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\Tom\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Tom\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Tom\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\Tom\stable-diffusion-webui\modules\api\api.py", line 375, in img2imgapi
    processed = process_images(p)
  File "C:\Users\Tom\stable-diffusion-webui\modules\processing.py", line 515, in process_images
    res = process_images_inner(p)
  File "C:\Users\Tom\stable-diffusion-webui\modules\processing.py", line 604, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "C:\Users\Tom\stable-diffusion-webui\modules\processing.py", line 1084, in init
    self.init_latent = self.sd_model.get_first_stage_encoding(self.sd_model.encode_first_stage(image))
  File "C:\Users\Tom\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "C:\Users\Tom\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "C:\Users\Tom\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Tom\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 830, in encode_first_stage
    return self.first_stage_model.encode(x)
  File "C:\Users\Tom\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\autoencoder.py", line 83, in encode
    h = self.encoder(x)
  File "C:\Users\Tom\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Tom\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 526, in forward
    h = self.down[i_level].block[i_block](hs[-1], temb)
  File "C:\Users\Tom\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Tom\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 138, in forward
    h = self.norm2(h)
  File "C:\Users\Tom\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Tom\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\normalization.py", line 273, in forward
    return F.group_norm(
  File "C:\Users\Tom\stable-diffusion-webui\venv\lib\site-packages\torch\nn\functional.py", line 2530, in group_norm
    return torch.group_norm(input, num_groups, weight, bias, eps, torch.backends.cudnn.enabled)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 4.00 GiB total capacity; 2.34 GiB already allocated; 0 bytes free; 2.49 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### Environment

- Blender version (upper right corner of splash screen): 
- AI Render version (find in Preferences > Add-ons): 
- Operating system (Windows/Mac/Linux): 
version: 3.3.1, branch: master, commit date: 2022-10-04 18:35, hash: b292cfe5a936, type: release
build date: 2022-10-05, 00:49:25
platform: 'Windows-10-10.0.22621-SP0'

Device name	MSI
Processor	Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz   2.60 GHz
Installed RAM	32.0 GB (31.8 GB usable)
Device ID	*************************************
Product ID	*********************************
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
 NVIDIA GeForce GTX 1650

### Screenshots/video

![Screenshot (24)](https://github.com/benrugg/AI-Render/assets/37158298/d566bbba-2784-4925-b500-e7b88b44e6a7)

**Comment by benrugg** [comment]
Hey, glad you're enjoying AI Render. As far as setup of Automatic1111, python versions, etc, all of that is outside of AI Render. You can post this on the Automatic1111 issues, though: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues

(I don't have anything to do with that project - I just integrated with it as a way of allowing local installation).
