### ISSUE TITLE
Getting a KeyError: None when Upscaling

### ISSUE THREAD

**Issue by GeminiSquishGames** [benrugg/AI-Render#144]
### Describe the bug

I render an image and then generate. If automatic upscale or manual upscale, get the following error:

An error occurred in the Automatic1111 Stable Diffusion server. Check the server logs for more info.

```
*** API error: POST: http://127.0.0.1:7860/sdapi/v1/extra-single-image {'error': 'KeyError', 'detail': '', 'body': '', 'errors': 'None'}
    Traceback (most recent call last):
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\anyio\streams\memory.py", line 98, in receive
        return self.receive_nowait()
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\anyio\streams\memory.py", line 93, in receive_nowait
        raise WouldBlock
    anyio.WouldBlock

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
        message = await recv_stream.receive()
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\anyio\streams\memory.py", line 118, in receive
        raise EndOfStream
    anyio.EndOfStream

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\modules\api\api.py", line 190, in exception_handling
        return await call_next(request)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
        response = await self.dispatch_func(request, call_next)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\modules\api\api.py", line 154, in log_and_time
        res: Response = await call_next(req)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
        await self.app(scope, receive, send)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
        await responder(scope, receive, send)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
        await self.app(scope, receive, self.send_with_gzip)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
        raise exc
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
        await self.app(scope, receive, sender)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
        raise e
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
        await self.app(scope, receive, send)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
        await route.handle(scope, receive, send)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\starlette\routing.py", line 276, in handle
        await self.app(scope, receive, send)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\starlette\routing.py", line 66, in app
        response = await func(request)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\fastapi\routing.py", line 237, in app
        raw_response = await run_endpoint_function(
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
        return await run_in_threadpool(dependant.call, **values)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
        return await anyio.to_thread.run_sync(func, *args)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
        return await get_asynclib().run_sync_in_worker_thread(
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
        return await future
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
        result = context.run(func, *args)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\modules\api\api.py", line 576, in extras_single_image_api
        result = postprocessing.run_extras(extras_mode=0, image_folder="", input_dir="", output_dir="", save_output=False, **reqDict)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\modules\postprocessing.py", line 161, in run_extras
        return run_postprocessing(extras_mode, image, image_folder, input_dir, output_dir, show_extras_results, *args, save_output=save_output)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\modules\postprocessing.py", line 71, in run_postprocessing
        scripts.scripts_postproc.run(initial_pp, args)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\modules\scripts_postprocessing.py", line 196, in run
        script.process(single_image, **process_args)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-pixelart\scripts\postprocessing_pixelart.py", line 112, in process
        dither = DITHER_METHODS[dither_method]
    KeyError: None

---
```

Blender 4.1
SD server is 

### To reproduce

Render a scene and either auto or manually generate it. Then have either automatic upscale on or do a manual upscale. Upscale is the thing. Try reloading or different upscale models, the same result.

### Error log

An error occurred in the Automatic1111 Stable Diffusion server. Check the server logs for more info.

```
*** API error: POST: http://127.0.0.1:7860/sdapi/v1/extra-single-image {'error': 'KeyError', 'detail': '', 'body': '', 'errors': 'None'}
    Traceback (most recent call last):
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\anyio\streams\memory.py", line 98, in receive
        return self.receive_nowait()
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\anyio\streams\memory.py", line 93, in receive_nowait
        raise WouldBlock
    anyio.WouldBlock

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
        message = await recv_stream.receive()
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\anyio\streams\memory.py", line 118, in receive
        raise EndOfStream
    anyio.EndOfStream

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\modules\api\api.py", line 190, in exception_handling
        return await call_next(request)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
        response = await self.dispatch_func(request, call_next)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\modules\api\api.py", line 154, in log_and_time
        res: Response = await call_next(req)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
        await self.app(scope, receive, send)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
        await responder(scope, receive, send)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
        await self.app(scope, receive, self.send_with_gzip)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
        raise exc
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
        await self.app(scope, receive, sender)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
        raise e
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
        await self.app(scope, receive, send)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
        await route.handle(scope, receive, send)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\starlette\routing.py", line 276, in handle
        await self.app(scope, receive, send)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\starlette\routing.py", line 66, in app
        response = await func(request)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\fastapi\routing.py", line 237, in app
        raw_response = await run_endpoint_function(
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
        return await run_in_threadpool(dependant.call, **values)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
        return await anyio.to_thread.run_sync(func, *args)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
        return await get_asynclib().run_sync_in_worker_thread(
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
        return await future
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
        result = context.run(func, *args)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\modules\api\api.py", line 576, in extras_single_image_api
        result = postprocessing.run_extras(extras_mode=0, image_folder="", input_dir="", output_dir="", save_output=False, **reqDict)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\modules\postprocessing.py", line 161, in run_extras
        return run_postprocessing(extras_mode, image, image_folder, input_dir, output_dir, show_extras_results, *args, save_output=save_output)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\modules\postprocessing.py", line 71, in run_postprocessing
        scripts.scripts_postproc.run(initial_pp, args)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\modules\scripts_postprocessing.py", line 196, in run
        script.process(single_image, **process_args)
      File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-pixelart\scripts\postprocessing_pixelart.py", line 112, in process
        dither = DITHER_METHODS[dither_method]
    KeyError: None

---
```

### Environment

Blender 4.1
AI Render 1.0.1
Windows 10

**Comment by benrugg** [comment]
It looks like this is an error in Automatic1111 rather than AI Render. I don't have a great way to help with this, but you can try reaching out on their github page!
