### ISSUE TITLE
The render image don't change

### ISSUE THREAD

**Issue by ajayboss-IN** [benrugg/AI-Render#15]
### Describe the bug

Every time i click render but it not change the render image.I try youtube tutorial but it not work at all help me& thank you.
![Screenshot (269)](https://user-images.githubusercontent.com/63161359/197347272-06754403-954f-4056-87dc-766cce662477.png)

### To reproduce

1)install addon and connect to api
2)create a sample scene
3)click to render 

### Error log

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

### Environment

- Blender version (upper right corner of splash screen): 
- AI Render version (find in Preferences > Add-ons): 
- Operating system (Windows):

**Comment by benrugg** [comment]
Looks like the root of the error is that it can't connect to the website for DreamStudio. My best guess is that you have a proxy or VPN that is causing the issue. Are you using anything special to connect to the internet (or are you on a managed internet connection, like at a company or school)?
