### ISSUE TITLE
SSL Connection Error

### ISSUE THREAD

**Issue by ohmygardn** [benrugg/AI-Render#40]
### Describe the bug

I've read all closed isssues on this problem but nothing helped.  The same problem each time - doesn't render and the node is muted (as on the picture).

### To reproduce

press F12 and doesn't work

### Error log

Read prefs: C:\Users\79963\AppData\Roaming\Blender Foundation\Blender\3.3\config\userpref.blend
Read blend: C:\Users\79963\Desktop\3D\first works\try ai.blend
GPUTexture: Blender Texture Not Loaded!
GPUTexture: Blender Texture Not Loaded!
GPUTexture: Blender Texture Not Loaded!
GPUTexture: Blender Texture Not Loaded!
GPUTexture: Blender Texture Not Loaded!
GPUTexture: Blender Texture Not Loaded!
GPUTexture: Blender Texture Not Loaded!
GPUTexture: Blender Texture Not Loaded!
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\urllib3\connectionpool.py", line 994, in _prepare_proxy
    conn.connect()
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\urllib3\connection.py", line 364, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\urllib3\connection.py", line 501, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='c7vllddffse76obdapr6s2p4du0ydjrn.lambda-url.us-west-2.on.aws', port=443): Max retries exceeded with url: /?prompt=two+princesses+are+sitting+on+the+beach+near+the+sea%2C+oil%2C+beautiful+portrait%2C+8k+resolution+concept+art+portrait%2C+hyperdetailed%2C+intricately+detailed%2C+trending+on+Artstation%2C+triadic+colors%2C+volumetric+lighting%2C+soft+focus%2C+dynamic+lighting&width=512&height=512&image_similarity=0.1899999976158142&seed=1672575428&cfg_scale=7.0&steps=40&sampler=k_lms (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\79963\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\AI-Render\task_queue.py", line 12, in execute_queued_functions
    function()
  File "C:\Users\79963\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\AI-Render\operators.py", line 471, in send_to_api
    output_file = dreamstudio_api.send_to_api(params, img_file, after_output_filename_prefix)
  File "C:\Users\79963\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\AI-Render\sd_backends\dreamstudio\dreamstudio_api.py", line 27, in send_to_api
    response = requests.post(config.API_URL, params=params, headers=headers, files=files, timeout=config.request_timeout)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='c7vllddffse76obdapr6s2p4du0ydjrn.lambda-url.us-west-2.on.aws', port=443): Max retries exceeded with url: /?prompt=two+princesses+are+sitting+on+the+beach+near+the+sea%2C+oil%2C+beautiful+portrait%2C+8k+resolution+concept+art+portrait%2C+hyperdetailed%2C+intricately+detailed%2C+trending+on+Artstation%2C+triadic+colors%2C+volumetric+lighting%2C+soft+focus%2C+dynamic+lighting&width=512&height=512&image_similarity=0.1899999976158142&seed=1672575428&cfg_scale=7.0&steps=40&sampler=k_lms (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
Warning: Object has non-uniform scale, sculpting may be unpredictable

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy_types.py", line 877, in draw_ls
    def draw_ls(self, context):
KeyboardInterrupt

### Environment

- Blender version (upper right corner of splash screen): 3.3.1
- AI Render version (find in Preferences > Add-ons): 0.5.3
- Operating system (Windows/Mac/Linux): Windows

### Screenshots/video

<img width="347" alt="image" src="https://user-images.githubusercontent.com/118317458/202046398-47a43b79-9481-4a66-a8aa-a0161f82364c.png">

**Comment by benrugg** [comment]
Thank you for posting the detailed logs. It looks like it's having an SSL connection error, so something about your internet configuration is blocking the connection to the server. 

Is there something about your network or you computer that would modify or restrict the internet? A proxy, VPN or some kind of configuration by an IT department or school?

**Comment by ohmygardn** [comment]
Thanks a lot! I took time but finally I solved 
![ai-render-1669187993-2-after](https://user-images.githubusercontent.com/118317458/203491486-483ed4b6-d7e5-412e-8ce2-f9a26e36a525.png)

**Comment by benrugg** [comment]
Great! Could you actually let me know what you did to solve it? I've seen a couple other folks have this issue as well.

**Comment by ohmygardn** [comment]
Yeah, actually it was the problem with proxy, I had a few of them and couldn't turn them off. 

https://www.ssl2buy.com/wiki/how-to-fix-err-ssl-protocol-error this article helped me, I fixed it with first three points.

**Comment by benrugg** [comment]
Awesome - thank you so much for letting me know. I will share that with anyone else who has a similar issue!
