### ISSUE TITLE
Traceback (Most recent call last)

### ISSUE THREAD

**Issue by sujeshpullanikkat** [benrugg/AI-Render#41]
### Describe the bug

![image](https://user-images.githubusercontent.com/114976186/202608638-c8ca769e-265f-4440-99db-4f01776accd4.png)

### To reproduce

Its not getting enabled once after instiing the plugin

### Error log

Read prefs: C:\Users\Sujesh Pullanikkat\AppData\Roaming\Blender Foundation\Blender\2.83\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender 2.83\2.83\python
reloading addon: AI-Render 1668740773.6741736 1668740883.0887089 'C:\\Users\\Sujesh Pullanikkat\\AppData\\Roaming\\Blender Foundation\\Blender\\2.83\\scripts\\addons\\AI-Render\\__init__.py'
Modules Installed () from 'F:\\SOFTWARES\\Blender\\AI-Render-v0-5-3.zip' into 'C:\\Users\\Sujesh Pullanikkat\\AppData\\Roaming\\Blender Foundation\\Blender\\2.83\\scripts\\addons'
TypeError: EnumProperty(...): 'default' can't be set when 'items' is a function
Exception in module register(): C:\Users\Sujesh Pullanikkat\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\AI-Render\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Users\Sujesh Pullanikkat\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\AI-Render\__init__.py", line 58, in register
    properties.register()
  File "C:\Users\Sujesh Pullanikkat\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\AI-Render\properties.py", line 179, in register
    bpy.utils.register_class(cls)
ValueError: bpy_struct "AIRProperties" registration error: sampler could not register

Exception in module register(): C:\Users\Sujesh Pullanikkat\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\AI-Render\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Users\Sujesh Pullanikkat\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\AI-Render\__init__.py", line 53, in register
    addon_updater_ops.register(bl_info)
  File "C:\Users\Sujesh Pullanikkat\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\AI-Render\addon_updater_ops.py", line 1516, in register
    bpy.utils.register_class(cls)
ValueError: register_class(...): already registered as a subclass 'AddonUpdaterInstallPopup'

reloading addon: AI-Render 1668740883.0887089 1668741004.0677583 'C:\\Users\\Sujesh Pullanikkat\\AppData\\Roaming\\Blender Foundation\\Blender\\2.83\\scripts\\addons\\AI-Render\\__init__.py'
Modules Installed () from 'F:\\SOFTWARES\\Blender\\AI-Render-v0-5-3.zip' into 'C:\\Users\\Sujesh Pullanikkat\\AppData\\Roaming\\Blender Foundation\\Blender\\2.83\\scripts\\addons'
Exception in module register(): C:\Users\Sujesh Pullanikkat\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\AI-Render\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Users\Sujesh Pullanikkat\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\AI-Render\__init__.py", line 53, in register
    addon_updater_ops.register(bl_info)
  File "C:\Users\Sujesh Pullanikkat\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\AI-Render\addon_updater_ops.py", line 1516, in register
    bpy.utils.register_class(cls)
ValueError: register_class(...): already registered as a subclass 'AddonUpdaterInstallPopup'

Exception in module register(): C:\Users\Sujesh Pullanikkat\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\AI-Render\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Users\Sujesh Pullanikkat\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\AI-Render\__init__.py", line 53, in register
    addon_updater_ops.register(bl_info)
  File "C:\Users\Sujesh Pullanikkat\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\AI-Render\addon_updater_ops.py", line 1516, in register
    bpy.utils.register_class(cls)
ValueError: register_class(...): already registered as a subclass 'AddonUpdaterInstallPopup'

Exception in module register(): C:\Users\Sujesh Pullanikkat\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\AI-Render\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Users\Sujesh Pullanikkat\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\AI-Render\__init__.py", line 53, in register
    addon_updater_ops.register(bl_info)
  File "C:\Users\Sujesh Pullanikkat\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\AI-Render\addon_updater_ops.py", line 1516, in register
    bpy.utils.register_class(cls)
ValueError: register_class(...): already registered as a subclass 'AddonUpdaterInstallPopup'

Exception in module register(): C:\Users\Sujesh Pullanikkat\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\AI-Render\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Users\Sujesh Pullanikkat\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\AI-Render\__init__.py", line 53, in register
    addon_updater_ops.register(bl_info)
  File "C:\Users\Sujesh Pullanikkat\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\AI-Render\addon_updater_ops.py", line 1516, in register
    bpy.utils.register_class(cls)
ValueError: register_class(...): already registered as a subclass 'AddonUpdaterInstallPopup'

Exception in module register(): C:\Users\Sujesh Pullanikkat\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\AI-Render\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Users\Sujesh Pullanikkat\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\AI-Render\__init__.py", line 53, in register
    addon_updater_ops.register(bl_info)
  File "C:\Users\Sujesh Pullanikkat\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\AI-Render\addon_updater_ops.py", line 1516, in register
    bpy.utils.register_class(cls)
ValueError: register_class(...): already registered as a subclass 'AddonUpdaterInstallPopup'

Exception in module register(): C:\Users\Sujesh Pullanikkat\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\AI-Render\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Users\Sujesh Pullanikkat\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\AI-Render\__init__.py", line 53, in register
    addon_updater_ops.register(bl_info)
  File "C:\Users\Sujesh Pullanikkat\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\AI-Render\addon_updater_ops.py", line 1516, in register
    bpy.utils.register_class(cls)
ValueError: register_class(...): already registered as a subclass 'AddonUpdaterInstallPopup'

Exception in module register(): C:\Users\Sujesh Pullanikkat\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\AI-Render\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Users\Sujesh Pullanikkat\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\AI-Render\__init__.py", line 53, in register
    addon_updater_ops.register(bl_info)
  File "C:\Users\Sujesh Pullanikkat\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\AI-Render\addon_updater_ops.py", line 1516, in register
    bpy.utils.register_class(cls)
ValueError: register_class(...): already registered as a subclass 'AddonUpdaterInstallPopup'

### Environment

- Blender version (upper right corner of splash screen): 
- AI Render version (find in Preferences > Add-ons): 
- Operating system (Windows/Mac/Linux): 

### Screenshots/video

![image](https://user-images.githubusercontent.com/114976186/202608927-5046a2b5-0113-4c9e-8ebb-c75b4d841e09.png)

**Comment by marianobasti** [comment]
I had that happen to me when removing and adding the addon while doing tests. Looks like some things aren't unregistering when removing it?
Anyway, restarting Blender always fixed it for me.

**Comment by benrugg** [comment]
Thanks for confirming that, @marianobasti

**Comment by Chuntestev72674** [comment]
Hi, I am having the same exact issue. Restarting Blender has unfortunately not fixed it for me.
