### ISSUE TITLE
Error with Automatic1111: Unexpected keyword argument `include_init_images`

### ISSUE THREAD

**Issue by a70m123r** [benrugg/AI-Render#42]
### Describe the bug

Was working few days ago, did the latest 1111 update, tried to render something in blender and got the following message "An error occurred in the Automatic1111 Stable Diffusion server. Check the server logs for more info." not sure where to find the logs...

### To reproduce

latest 1111 and AI render addon 

### Error log

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 94, in receive
    return self.receive_nowait()
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 43, in call_next
    message = await recv_stream.receive()
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 72, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\ai\stable-diffusion-webui\extensions\auto-sd-paint-ext\backend\app.py", line 344, in app_encryption_middleware
    res: StreamingResponse = await call_next(req)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 46, in call_next
    raise app_exc
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 36, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 43, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\ai\stable-diffusion-webui\modules\api\api.py", line 149, in img2imgapi
    p = StableDiffusionProcessingImg2Img(**vars(populate))
  File "C:\ai\stable-diffusion-webui\modules\processing.py", line 736, in __init__
    super().__init__(**kwargs)
TypeError: StableDiffusionProcessing.__init__() got an unexpected keyword argument 'include_init_images'

### Environment

- Blender version (upper right corner of splash screen): 3.3
- AI Render version (find in Preferences > Add-ons): 05.03
- Operating system (Windows/Mac/Linux): Windows 10

**Comment by marianobasti** [comment]
You can find the logs in A1111's CLI window, when you execute webui-user.bat

**Comment by a70m123r** [comment]
Added the error log

**Comment by marianobasti** [comment]
There were a bunch of commits yesterday, that might have broken something.
Can you try running an img2img test on the webui? If that works, it must be something on AI-render's side, specifically when passing arguments to the api

**Comment by a70m123r** [comment]
> There were a bunch of commits yesterday, that might have broken something. Can you try running an img2img test on the webui? If that works, it must be something on AI-render's side, specifically when passing arguments to the api

img2img is working fine, think too that the latest update broke something.

**Comment by benrugg** [comment]
Hmm, just updated Automatic1111 and everything is still working fine on my end. Not sure what's going on... the error you're seeing is definitely related to a recent update. `include_init_images` is new. 

I would have thought the same thing @marianobasti suggested - that img2img in the web ui would be broken. But since that's not the case, I honestly don't know what else to try at the moment...

**Comment by marianobasti** [comment]
Yeah, it looks like an API/modules problem. .On here httpsgithub.comAUTOMATIC1111stable-diffusion-webuipull3577(url) someone introduces the `include_init_images` argument to fix something with Python 3.7. @a70m123r what is your version?

**Comment by a70m123r** [comment]
> Yeah, it looks like an API/modules problem. Here [https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/3577](url) someone introduces the `include_init_images` argument to fix something with Python 3.7. @a70m123r what is your version?

Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)] on win32, should I update to 3.7?

**Comment by a70m123r** [comment]
> Hmm, just updated Automatic1111 and everything is still working fine on my end. Not sure what's going on... the error you're seeing is definitely related to a recent update. `include_init_images` is new.
> 
> I would have thought the same thing @marianobasti suggested - that img2img in the web ui would be broken. But since that's not the case, I honestly don't know what else to try at the moment...

Think l'll try a fresh install, see if it resolves the issue. Really keen to play around with it some more!

**Comment by a70m123r** [comment]
Tried it with a new install of stable diffusion and the addon is working as it should, nice! I think it was some addon or an option is settings, just glad it fixed the issue.

**Comment by benrugg** [comment]
Great. Glad to hear you got it working!
