### ISSUE TITLE
Timeout when integrating with Diffusion Bee

### ISSUE THREAD

**Issue by enzyme69** [benrugg/AI-Render#5]
### Describe the bug

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/blendersushi/Library/Application Support/Blender/3.4/scripts/addons/AI-Render/task_queue.py", line 12, in execute_queued_functions
    function()
  File "/Users/blendersushi/Library/Application Support/Blender/3.4/scripts/addons/AI-Render/operators.py", line 278, in send_to_api
    response = requests.post(config.API_URL, params=params, headers=headers, files=files, timeout=config.request_timeout)
  File "/Applications/BLENDER_34/Blender.app/Contents/Resources/3.4/python/lib/python3.10/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Applications/BLENDER_34/Blender.app/Contents/Resources/3.4/python/lib/python3.10/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Applications/BLENDER_34/Blender.app/Contents/Resources/3.4/python/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Applications/BLENDER_34/Blender.app/Contents/Resources/3.4/python/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/Applications/BLENDER_34/Blender.app/Contents/Resources/3.4/python/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', TimeoutError('The write operation timed out'))

```

### To reproduce

I was running this AI render while also doing Diffusion Bee (tasking stuff). And I kept getting this time out issue and no render being produced.

### Expected behavior

It should just work.

### Environment

- AI Render version: latest
- Blender version: 3.4
- Operating system: macOS Ventura

**Comment by benrugg** [comment]
Interesting... I will check this out.

**Comment by enzyme69** [comment]
It could be my wifi network however, so maybe user with slow connection experience this.

Detailed logs in the terminal could help to inform the user, or like maybe showing how much credit left on the Dream Studio.

**Comment by benrugg** [comment]
I haven't tested this out with Diffusion Bee, but I just released a new version of AI Render that uses a different API on the backend. If you still see a timeout with the new version, please re-open this issue!

Update AI Render in the add-on preferences or get the new version here: https://github.com/benrugg/AI-Render/releases/tag/v0.6.3
