### ISSUE TITLE
Traceback (Most Recent Call) Issue Not Resolved

### ISSUE THREAD

**Issue by Chuntestev72674** [benrugg/AI-Render#69]
### Describe the bug

https://github.com/benrugg/AI-Render/issues/41#issue-1454367904

Same exact issue as the one linked above. Bug appears after attempting to install plug-in in Blender. #

### To reproduce

Install zip file to preferences. 

### Error log

Exception in module register(): C:\Users\estev\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\AI-Render\__init__.py
Traceback (most recent call last):
  File "D:\Gaming & Animation Engines\Blender Foundation\Blender\2.80\scripts\modules\addon_utils.py", line 384, in enable
    mod.register()
  File "C:\Users\estev\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\AI-Render\__init__.py", line 59, in register
    addon_updater_ops.register(bl_info)
  File "C:\Users\estev\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\AI-Render\addon_updater_ops.py", line 1522, in register
    bpy.utils.register_class(cls)
ValueError: register_class(...): already registered as a subclass

### Environment

- Blender version (upper right corner of splash screen): 
- AI Render version (find in Preferences > Add-ons): 
- Operating system (Windows/Mac/Linux): 

### Screenshots/video

![Blender Preferences 2_10_2023 10_49_39 AM](https://user-images.githubusercontent.com/62954218/218136229-d4aa179f-d129-4ea6-a165-d95f62e86581.png)
![Blender Preferences 2_10_2023 10_49_46 AM](https://user-images.githubusercontent.com/62954218/218136245-395320f4-5db7-4882-9913-4e590d1a2388.png)

### Additional information

Restarting blender does not do anything on my end. Same error appears no matter the amount of times I restart the program, my computer, or add/remove the add-on.

**Comment by benrugg** [comment]
Thank you for posting this again. I'm sorry it's happening for you! I just looked at this log and the one from #41. It looks like both are from Blender 2.8x. That's not actually a supported version for AI Render. It only officially works in 3.0+. 

I would try to make it work for 2.83, since I know that's still a LTS version, but in my testing earlier, I had all sorts of python errors that I couldn't debug.

**Comment by benrugg** [comment]
Actually, I will leave this open. Maybe someone who knows older versions of Blender can fix it!

**Comment by rcampos0** [comment]
I am using upbge 0.34 and i had found problem with the plugin 
![ai_render_comfy_problemas](https://github.com/user-attachments/assets/83178a2a-26ce-44ec-8d99-d7a519c0b4b2)

**Comment by benrugg** [comment]
@rcampos0 can you post a [new issue here](https://github.com/benrugg/AI-Render/issues/new?assignees=&labels=&projects=&template=bug-report.yaml), and then I can tag the right person, since it's an issue involving Comfy
