### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dapa5900** [benrugg/AI-Render#7]
Hi,

thanks a lot for the add-on, but unfortunately it doesn't work in my case. Please see below the error I get aft rendering:

![image](https://user-images.githubusercontent.com/75205162/196363939-52d6cf64-b11f-4cef-a411-b8f36adcbe4e.png)

The compositing node is also muted but even when I unmute it, it doesn't work.

**Comment by benrugg** [comment]
@dapa5900 Thanks for posting the error message. I'll do my best to figure out what is happening here. That error is unfortunately just a snippet of a longer one. Could you send the full log?

- On Windows, in Blender, you can go to Window > Toggle Error Console
- On Mac, start a Terminal window, then run `cd /Applications/Blender.app/Contents/MacOS && ./Blender` and you'll see the log in the terminal window once the error happens

**Comment by Rxrehy** [comment]
AI Render Error:  Something went wrong trying to create this image. Full error: Traceback (most recent call last):
  File "/var/lang/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/var/lang/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/var/task/stability_sdk/client.py", line 446, in <module>
    args.init_image = Image.open(args.init_image)
  File "/var/task/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file '/tmp/input-image-1666112094.251164.png'

**Comment by benrugg** [comment]
@Rxrehy Ok, great, that helps a lot. I think this is related to a couple of the other bug reports. Hopefully I can get this fixed asap!

**Comment by Rxrehy** [comment]
Yup, first I had that temp folder issue so after fixing that, I got this error.

**Comment by benrugg** [comment]
@Rxrehy Ah, ok, that's helpful info, too. I think it's related. I'm pretty sure it's just not getting permission from the operating system to create files. I'm working on it now...

**Comment by benrugg** [comment]
@Rxrehy @dapa5900 Could you try testing this update (attached)? Remove the existing add-on and install this one. Crossing my fingers... I think this should work.

[AI-Render-v0-2-7.zip](https://github.com/benrugg/AI-Render/files/9815634/AI-Render-v0-2-7.zip)

**Comment by dapa5900** [comment]
@benrugg  Yeah, it's working now. Thanks a lot! :-)

**Comment by benrugg** [comment]
@dapa5900 Great, thank you for testing it for me!

**Comment by benrugg** [comment]
Fixed in the latest release. Get it from Blender Market, Gumroad or the [releases page](https://github.com/benrugg/AI-Render/releases/tag/v0.2.8)

Or update in Blender under 'Preferences' > 'Add-ons' > 'AI Render' > 'Updates'

Fixed in a8d18a059e24442f95104e080c71c6ed2d106ae1 and 2db43b2a93a10a3034db9eb6d7e725dfab4db4f3
