### ISSUE TITLE
Blender AI Render animation error

### ISSUE THREAD

**Issue by 80primalzen08** [benrugg/AI-Render#82]
### Describe the bug

![Blender 3_27_2023 11_13_18 AM](https://user-images.githubusercontent.com/129091943/228002678-3106117f-e8d9-4a8b-a0ef-ba283eee49ef.png)

AI Render gives error for an Animation when trying to render a single image.

### To reproduce

Even with most basic scene ( plane, box, camera, point light ), enable AI Render, select desired prompts and settings ( left to default for purpose of report ), select Render at top left of screen or press F12. Will attempt to render, then gives error in AI Render panel.

### Error log

AI Render Error: To render an animation with AI Render, use the "Render Animation" button in the Animation panel below

### Environment

- Blender version (upper right corner of splash screen): 
- AI Render version (find in Preferences > Add-ons): 
- Operating system (Windows/Mac/Linux): 
Blender version 3.3.1
AI Render version 0.6.10
Windows 10 OS

### Screenshots/video

![Blender Preferences 3_27_2023 11_12_38 AM](https://user-images.githubusercontent.com/129091943/228005175-7784e0ec-976d-460a-b810-b73bca662b6e.png)
![Blender 3_27_2023 11_13_18 AM](https://user-images.githubusercontent.com/129091943/228005200-522fe104-7478-4e7e-ba48-8c29e27b14d8.png)

**Comment by benrugg** [comment]
Thanks for taking the time to post this here! I am trying on my end and still can't replicate. My first guess is that it's another add-on you have installed. Could you send me a screenshot of all the enabled add-ons you have? (in the add-on preferences panel, you can check `enabled add-ons only` and then resize the window). Thank you!

**Comment by 80primalzen08** [comment]
![Blender Preferences 3_27_2023 11_45_19 AM](https://user-images.githubusercontent.com/129091943/228007989-7ad9b2c0-ce51-48cb-bf1b-0ee4910ebdea.png)
![Blender Preferences 3_27_2023 11_45_33 AM](https://user-images.githubusercontent.com/129091943/228007995-d9ce7077-ade5-4c8e-9b46-3dcee56758bb.png)
![Blender Preferences 3_27_2023 11_45_46 AM](https://user-images.githubusercontent.com/129091943/228007999-c10f6ffe-d5e4-4d50-bb33-7e934115a7a9.png)
![Blender Preferences 3_27_2023 11_45_51 AM](https://user-images.githubusercontent.com/129091943/228008000-de50955c-ca61-47ad-9f2d-5f053cb83afb.png)

**Comment by 80primalzen08** [comment]
I've tried replicating everything I've seen in all the tutorial videos I could find, but they were all posted months ago. The Operations and Animations tabs have been added, but thats the only difference, so I leave those default. I press F12 or use the Render tab at the top left for a single image and it gives me that animation error and renders either no detail or renders a black screen.

**Comment by benrugg** [comment]
Thanks for posting that. You do have a lot of add-ons installed, so this theory is seeming promising. Can you try disabling Animall and Commotion and see if that fixes it? (Make sure to restart blender after disabling them before trying AI Render again)

**Comment by 80primalzen08** [comment]
![Screenshot (7)](https://user-images.githubusercontent.com/129091943/228022853-326eeef8-c5d7-4166-a4ff-e26837f9f415.png)

Still giving the same. I have to render an image that fails, it cost me points, then I have to go through the Operations dropdown in the AI Render panel, select "New Image from Last Render" only then does it work but only on the most basic of prompts and settings. And costs points again. Im not worried about the points, but it would be nice to get some results like I've seen in the tutorial videos.

![Blender_  D__Blender_Projects_default scene blend  3_27_2023 12_48_17 PM](https://user-images.githubusercontent.com/129091943/228023547-2ef3fda4-203a-4978-99fe-6f68f5ae5482.png)

**Comment by benrugg** [comment]
If you want to upload an example .blend file, I'll see if there's something about the file/scene itself that could be causing this.

**Comment by 80primalzen08** [comment]
It won't let me add a .blend file to the thread. But it is still hitting me in the credits with DreamStudio.

**Comment by 80primalzen08** [comment]
I'll look at some of the other troubleshoots you've mentioned

**Comment by benrugg** [comment]
> But it is still hitting me in the credits with DreamStudio.

That is very strange. It must be doing something non-standard behind the scenes, because that error happens before AI Render sends to dreamstudio. So something must be causing it to render twice or do something in the background. It's almost got to be another add-on. (Or potentially some obscure Blender setting??). 

If you want to email me the .blend file, you can send it to airenderblender@gmail.com. 

And also, until we figure this out, if you want to avoid the double credits, you can turn off "Run Automatically on Render" under AI Render > Operation

**Comment by HanshustlerHHHH** [comment]
i have the same issue ..but its crazy because i could render two images and now i get always this error :D

**Comment by HanshustlerHHHH** [comment]
i will try it again right now in the past it worked without any problems.

i m using 
Blender 3.4
and the local processing with automatic1111 stable diffusion Web Ui ( 768-v-ema.ckpt ) 

i disabled dream texture 
![addons](https://user-images.githubusercontent.com/121248971/229118234-1f27f37b-6c46-4f83-b422-a241ae0a53ac.jpg)

i started the webui-user.bat 

thats the reply i get after i started rendering in eeve
To create a public link, set `share=True` in `launch()`.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\fastapi\routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\modules\api\api.py", line 175, in img2imgapi
    processed = process_images(p)
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\modules\processing.py", line 469, in process_images
    res = process_images_inner(p)
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\modules\processing.py", line 539, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\modules\processing.py", line 885, in init
    self.init_latent = self.sd_model.get_first_stage_encoding(self.sd_model.encode_first_stage(image))
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 830, in encode_first_stage
    return self.first_stage_model.encode(x)
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\repositories\stable-diffusion-stability-ai\ldm\models\autoencoder.py", line 83, in encode
    h = self.encoder(x)
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 526, in forward
    h = self.down[i_level].block[i_block](hs[-1], temb)
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 131, in forward
    h = self.norm1(h)
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\torch\nn\modules\normalization.py", line 272, in forward
    return F.group_norm(
  File "C:\Users\Bastl\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\torch\nn\functional.py", line 2516, in group_norm
    return torch.group_norm(input, num_groups, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: CUDA out of memory. Tried to allocate 1.17 GiB (GPU 0; 6.00 GiB total capacity; 4.23 GiB already allocated; 153.66 MiB free; 4.32 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by benrugg** [comment]
@HanshustlerHHHH thanks for posting the error log. That is actually an error with Automatic1111, not AI Render. It looks like it's trying to use more GPU memory than you have available. 

Automatic1111 has changed A LOT in the past few months, so it's totally plausible that it worked well before, but is having issues now. Or it might be the addition of ControlNet that is using more memory. Another possibility is that you're using a larger model or image size than before (768x768 instead of 512x512?). 

Can you try running img2img in the Automatic1111 web ui? (And enable controlnet in the web ui). That should give you the same error. If it doesn't, let me know.

**Comment by HanshustlerHHHH** [comment]
<3
