### ISSUE TITLE
Ai stops giving Ai renders after 1 or 2 renders

### ISSUE THREAD

**Issue by PretendForReal** [benrugg/AI-Render#85]
### Describe the bug

When I first start blender the Ai render works fine, but only for 2 or 3 renders and then it stops responding. It still renders the base blender render but the Ai node in the compositor remains greyed out. 

### To reproduce

Open project, enable Ai render, Aim camera. press F12. 

After 2 or 3 renders I will no longer get renders from Dream Studios coming through.

### Error log

  File "C:\Users\prete\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\AI-Render\handlers.py", line 41, in render_init_handler
    scene.air_props.is_rendering = True
AttributeError: Writing to ID classes in this context is not allowed: Scene, Scene datablock, error setting AIRProperties.is_rendering
Traceback (most recent call last):
  File "C:\Users\prete\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\photographer\handler.py", line 17, in update_render_camera
    camera_ob.data.photographer.ev = camera_ob_eval.data.photographer.ev
AttributeError: Writing to ID classes in this context is not allowed: Camera, Camera datablock, error setting PhotographerCameraSettings.ev
Traceback (most recent call last):
  File "C:\Users\prete\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\AI-Render\handlers.py", line 108, in render_complete_handler
    scene.air_props.is_rendering = False
AttributeError: Writing to ID classes in this context is not allowed: Scene, Scene datablock, error setting AIRProperties.is_rendering
Traceback (most recent call last):
  File "C:\Users\prete\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\AI-Render\handlers.py", line 41, in render_init_handler
    scene.air_props.is_rendering = True
AttributeError: Writing to ID classes in this context is not allowed: Scene, Scene datablock, error setting AIRProperties.is_rendering
Traceback (most recent call last):
  File "C:\Users\prete\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\photographer\handler.py", line 17, in update_render_camera
    camera_ob.data.photographer.ev = camera_ob_eval.data.photographer.ev
AttributeError: Writing to ID classes in this context is not allowed: Camera, Camera datablock, error setting PhotographerCameraSettings.ev
Traceback (most recent call last):
  File "C:\Users\prete\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\AI-Render\handlers.py", line 108, in render_complete_handler
    scene.air_props.is_rendering = False
AttributeError: Writing to ID classes in this context is not allowed: Scene, Scene datablock, error setting AIRProperties.is_rendering
Traceback (most recent call last):
  File "C:\Users\prete\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\photographer\handler.py", line 17, in update_render_camera
    camera_ob.data.photographer.ev = camera_ob_eval.data.photographer.ev
AttributeError: Writing to ID classes in this context is not allowed: Camera, Camera datablock, error setting PhotographerCameraSettings.ev
Traceback (most recent call last):
  File "C:\Users\prete\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\AI-Render\handlers.py", line 108, in render_complete_handler
    scene.air_props.is_rendering = False
AttributeError: Writing to ID classes in this context is not allowed: Scene, Scene datablock, error setting AIRProperties.is_rendering
Traceback (most recent call last):
  File "C:\Users\prete\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\AI-Render\handlers.py", line 41, in render_init_handler
    scene.air_props.is_rendering = True
AttributeError: Writing to ID classes in this context is not allowed: Scene, Scene datablock, error setting AIRProperties.is_rendering
Traceback (most recent call last):
  File "C:\Users\prete\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\photographer\handler.py", line 17, in update_render_camera
    camera_ob.data.photographer.ev = camera_ob_eval.data.photographer.ev
AttributeError: Writing to ID classes in this context is not allowed: Camera, Camera datablock, error setting PhotographerCameraSettings.ev
Traceback (most recent call last):
  File "C:\Users\prete\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\AI-Render\handlers.py", line 108, in render_complete_handler
    scene.air_props.is_rendering = False
AttributeError: Writing to ID classes in this context is not allowed: Scene, Scene datablock, error setting AIRProperties.is_rendering
Traceback (most recent call last):
  File "C:\Users\prete\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\AI-Render\handlers.py", line 41, in render_init_handler
    scene.air_props.is_rendering = True
AttributeError: Writing to ID classes in this context is not allowed: Scene, Scene datablock, error setting AIRProperties.is_rendering
Traceback (most recent call last):
  File "C:\Users\prete\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\photographer\handler.py", line 17, in update_render_camera
    camera_ob.data.photographer.ev = camera_ob_eval.data.photographer.ev
AttributeError: Writing to ID classes in this context is not allowed: Camera, Camera datablock, error setting PhotographerCameraSettings.ev
Traceback (most recent call last):
  File "C:\Users\prete\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\AI-Render\handlers.py", line 108, in render_complete_handler
    scene.air_props.is_rendering = False
AttributeError: Writing to ID classes in this context is not allowed: Scene, Scene datablock, error setting AIRProperties.is_rendering
Traceback (most recent call last):
  File "C:\Users\prete\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\AI-Render\handlers.py", line 41, in render_init_handler
    scene.air_props.is_rendering = True
AttributeError: Writing to ID classes in this context is not allowed: Scene, Scene datablock, error setting AIRProperties.is_rendering
Traceback (most recent call last):
  File "C:\Users\prete\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\photographer\handler.py", line 17, in update_render_camera
    camera_ob.data.photographer.ev = camera_ob_eval.data.photographer.ev
AttributeError: Writing to ID classes in this context is not allowed: Camera, Camera datablock, error setting PhotographerCameraSettings.ev
Traceback (most recent call last):
  File "C:\Users\prete\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\AI-Render\handlers.py", line 108, in render_complete_handler
    scene.air_props.is_rendering = False
AttributeError: Writing to ID classes in this context is not allowed: Scene, Scene datablock, error setting AIRProperties.is_rendering

### Environment

- Blender version (upper right corner of splash screen): 3.4.1
- AI Render version (find in Preferences > Add-ons): 0.6.10
- Operating system (Windows/Mac/Linux):  Windows 

### Additional information

Using dream studio credits. But I have plenty in there..

**Comment by benrugg** [comment]
Ah, great, thank you for posting the log. This is a weird error I haven't seen before, but I will check more deeply into it as soon as I can. 

It looks like there's an error also happening with a different add-on you have: "photographer". Can you try disabling this add-on, restarting Blender, and then see if AI Render still has an issue after that?

**Comment by PretendForReal** [comment]
Will do. Unfortunately I only have an hour or two each morning to do my
personal projects before my day job as a commercial head of post. lol
Will jump back in tomorrow-

Meanwhile... once I do get it working. Any advice for best settings for
images already composed for 16x9?

Could that be the issue here btw? I have these all as UHD cams right now...

**Comment by benrugg** [comment]
> Any advice for best settings for images already composed for 16x9?

If you set the image size to 896 x 512, that is really close to 16:9.

(Because of the internals of Stable Diffusion, both the width and height have to be multiples of 64. It should work just fine at any size that it allows).

**Comment by PretendForReal** [comment]
hey! Thanks for the 896x512 tip and apparently it is Photographer Add-on
that was messing it up for some reason. Once I disabled that add-on it's
been working great... too bad as it's a great add-on to manage cameras with

**Comment by benrugg** [comment]
@PretendForReal glad to hear that that fixed it. I'll have to look into what is going on with the combo of our add-ons.
