### ISSUE TITLE
Automatic1111 Stable diffusion server error

### ISSUE THREAD

**Issue by osterstone** [benrugg/AI-Render#88]
### Describe the bug

I saw bug#82, but because my error message is different, i openend a seperate bug report.
My local SD installation runs without any problems, if I use it without Blender/Add-on.

The server log looks as follows:
=============================================================================
API error: POST: http://127.0.0.1:7860/sdapi/v1/img2img {'error': 'RuntimeError', 'detail': '', 'body': '', 'errors': "There is no current event loop in thread 'AnyIO worker thread'."}
Traceback (most recent call last):
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 94, in receive
    return self.receive_nowait()
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
    message = await recv_stream.receive()
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ai\stable-diffusion-webui\modules\api\api.py", line 145, in exception_handling
    return await call_next(request)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\ai\stable-diffusion-webui\modules\api\api.py", line 110, in log_and_time
    res: Response = await call_next(req)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc....lots of stuff folllowing

### To reproduce

I just use the standard cube, Prompt is "Cube".

### Error log

Read prefs: C:\Users\knutl\AppData\Roaming\Blender Foundation\Blender\3.5\config\userpref.blend
AI Render Error: An error occurred in the Automatic1111 Stable Diffusion server. Check the server logs for more info.

### Environment

- Blender version (upper right corner of splash screen): 3.5
- AI Render version (find in Preferences > Add-ons): 0.6.10
- Operating system (Windows/Mac/Linux): Windows

### Screenshots/video

![image](https://user-images.githubusercontent.com/78485504/230580104-589de1fa-fdd0-4f32-9024-a9fd2e5963b5.png)

### Additional information

I will test it on a second PC today or tomorrow

**Comment by osterstone** [comment]
I switched to Dreamstudio in the settings of the AddOn. I rendered just the standard cube and received  the normal render output and my credits at dreamstudio did not change. No errror message,

**Comment by benrugg** [comment]
PS. For the vast majority of users/installations, everything just works! I'm sorry about the issues you're experiencing!
