### ISSUE TITLE
Render fail

### ISSUE THREAD

**Issue by Hasley23** [benrugg/AI-Render#89]
### Describe the bug

Render didn't even start. 

### To reproduce

1. Start the server file .bat
2. Create new scene in Blender
3. Render didn't even start

### Error log

Read blend: D:\blenderWorks\AI Renders\sample.blend
AI Render Error: An error occurred in the Automatic1111 Stable Diffusion server. Check the server logs for more info.
INFO:ga4mp.ga4mp:Sending POST to: https://www.google-analytics.com/mp/collect
INFO:ga4mp.ga4mp:Batch Number: 1
INFO:ga4mp.ga4mp:Status code: 204

Server LOG:
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
    message = await recv_stream.receive()
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\venv\lib\site-packages\anyio\streams\memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\modules\api\api.py", line 145, in exception_handling
    return await call_next(request)
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\modules\api\api.py", line 110, in log_and_time
    res: Response = await call_next(req)
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\venv\lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\modules\api\api.py", line 374, in img2imgapi
    processed = process_images(p)
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\modules\processing.py", line 503, in process_images
    res = process_images_inner(p)
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\modules\processing.py", line 594, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\modules\processing.py", line 1056, in init
    self.init_latent = self.sd_model.get_first_stage_encoding(self.sd_model.encode_first_stage(image))
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 830, in encode_first_stage
    return self.first_stage_model.encode(x)
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\repositories\stable-diffusion-stability-ai\ldm\models\autoencoder.py", line 83, in encode
    h = self.encoder(x)
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 526, in forward
    h = self.down[i_level].block[i_block](hs[-1], temb)
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 131, in forward
    h = self.norm1(h)
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\venv\lib\site-packages\torch\nn\modules\normalization.py", line 273, in forward
    return F.group_norm(
  File "D:\StableDiffusionWebUI\stable-diffusion-webui-master\venv\lib\site-packages\torch\nn\functional.py", line 2528, in group_norm
    return torch.group_norm(input, num_groups, weight, bias, eps, torch.backends.cudnn.enabled)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 GiB (GPU 0; 6.00 GiB total capacity; 5.07 GiB already allocated; 0 bytes free; 5.08 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### Environment

- Blender version (upper right corner of splash screen):  3.4.1
- AI Render version (find in Preferences > Add-ons): 0.6.10
- Operating system (Windows/Mac/Linux): win 10 64-bit

### Additional information

Server just restarted. Everything worked fine before.

**Comment by benrugg** [comment]
Based on those logs, you're having an error in Automatic1111. There's not really a way for me to help with this, but you can ask their community for help. 

My quick diagnosis is that you might need to run it in low memory mode, since the error is that it ran out of memory. 

Once you can get Automatic1111 to work in their standard web ui (using img2img), then it will work with AI Render
