### ISSUE TITLE
Error when render animation 

### ISSUE THREAD

**Issue by C60nils** [benrugg/AI-Render#93]
### Describe the bug

Error message when using render animation button from plugin with local automatic1111 installation.  Single renders work fine.

### To reproduce

Blender 3.5, latest automatic 1111, ai-render addon 0.7.7.  Enable AI-render, Select output directory, hit render animation from within the AI-render tab, error message below

### Error log

Python: Traceback (most recent call last):
  File "/Users/c60/Library/Application Support/Blender/3.5/scripts/addons/AI-Render/operators.py", line 854, in execute
    if not self._pre_render(context):
  File "/Users/c60/Library/Application Support/Blender/3.5/scripts/addons/AI-Render/operators.py", line 732, in _pre_render
    do_pre_render_setup(scene)
  File "/Users/c60/Library/Application Support/Blender/3.5/scripts/addons/AI-Render/operators.py", line 223, in do_pre_render_setup
    mute_legacy_compositor_node_group(scene)
  File "/Users/c60/Library/Application Support/Blender/3.5/scripts/addons/AI-Render/operators.py", line 38, in mute_legacy_compositor_node_group
    legacy_node_group = scene.node_tree.nodes.get('AIR')
AttributeError: 'NoneType' object has no attribute 'nodes'

### Environment

- Blender version (upper right corner of splash screen): 3.5.0
- AI Render version (find in Preferences > Add-ons): 0.7.7
- Operating system (Windows/Mac/Linux): Linux, Mac

**Comment by Nadineli** [comment]
I have the exact same issue on Windows.

**Comment by benrugg** [comment]
Ah, interesting. Not sure why `scene.node_tree` wouldn't exist, but I just pushed a version that should fix it. Fixed in 9fdd374

Update AI Render through the add-on preferences (and make sure to restart Blender), or you can get the latest release here: https://github.com/benrugg/AI-Render/releases/tag/v0.7.8

Please let me know if for some reason you still get an error!

**Comment by benrugg** [comment]
Great, glad to hear it!
