### ISSUE TITLE
[Ermo 2] The system cannot find the path specified: 'C:\\Users\\username/.cache\\huggingface\\diffusers\\refs'

### ISSUE THREAD

**Issue by unt-pics** [benrugg/AI-Render#99]
### Describe the bug

Render end with error pop-up [Ermo 2] The system cannot find the path specified: 'C:\\Users\\username/.cache\\huggingface\\diffusers\\refs'

### To reproduce

Installed add-on as in the tutorial. Tried to render a default cube with local Stable Diffusion (automatic1111) with a prompt "metal box sci-fi"

### Error log

WARN (bpy.rna): C:\Users\blender\git\blender-v350\blender.git\source\blender\python\intern\bpy_rna.c:1341 pyrna_enum_to_py: current value '0' matches no enum in 'dream_textures.node_control_net', 'ControlNet', 'control_net'
WARN (bpy.rna): C:\Users\blender\git\blender-v350\blender.git\source\blender\python\intern\bpy_rna.c:1341 pyrna_enum_to_py: current value '0' matches no enum in 'DreamPrompt', '', 'model'
WARN (bpy.rna): C:\Users\blender\git\blender-v350\blender.git\source\blender\python\intern\bpy_rna.c:1341 pyrna_enum_to_py: current value '0' matches no enum in 'DreamPrompt', '', 'model'
Exception: Traceback (most recent call last):
  File "C:\Users\tarko\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\generator_process\actor.py", line 157, in _receive
    for res in iter(response):
  File "C:\Users\tarko\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\generator_process\actions\control_net.py", line 455, in control_net
    controlnet.append(load_pipe(self, f"control_net_model-{controlnet_name}", diffusers.ControlNetModel, controlnet_name, optimizations, None, device))
  File "C:\Users\tarko\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\generator_process\actions\prompt_to_image.py", line 63, in load_pipe
    snapshot_folder = model_snapshot_folder(model, revision)
  File "C:\Users\tarko\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\generator_process\actions\prompt_to_image.py", line 422, in model_snapshot_folder
    for revision in os.listdir(os.path.join(storage_folder, "refs")):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\tarko/.cache\\huggingface\\diffusers\\refs'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tarko\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\engine\engine.py", line 66, in render
    raise error
  File "C:\Users\tarko\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\engine\engine.py", line 58, in render
    group_outputs = node_executor.execute(scene.dream_textures_render_engine.node_tree, depsgraph, node_begin=node_begin, node_update=node_update, node_end=node_end, test_break=self.test_break)
  File "C:\Users\tarko\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\engine\node_executor.py", line 54, in execute
    result = execute_node(node, NodeExecutionContext(depsgraph, node_update, test_break), cache)
  File "C:\Users\tarko\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\engine\node_executor.py", line 37, in execute_node
Exception: Traceback (most recent call last):
  File "C:\Users\tarko\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\generator_process\actor.py", line 157, in _receive
    for res in iter(response):
  File "C:\Users\tarko\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\generator_process\actions\control_net.py", line 455, in control_net
    controlnet.append(load_pipe(self, f"control_net_model-{controlnet_name}", diffusers.ControlNetModel, controlnet_name, optimizations, None, device))
  File "C:\Users\tarko\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\generator_process\actions\prompt_to_image.py", line 63, in load_pipe
    snapshot_folder = model_snapshot_folder(model, revision)
  File "C:\Users\tarko\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\generator_process\actions\prompt_to_image.py", line 422, in model_snapshot_folder
    for revision in os.listdir(os.path.join(storage_folder, "refs")):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\tarko/.cache\\huggingface\\diffusers\\refs'

    result = node.execute(context, **kwargs)

The above exception was the direct cause of the following exception:

  File "C:\Users\tarko\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\engine\nodes\pipeline_nodes.py", line 243, in execute
Traceback (most recent call last):
  File "C:\Users\tarko\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\engine\engine.py", line 66, in render
    raise exception
  File "C:\Users\tarko\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\generator_process\future.py", line 100, in run_callbacks
    raise error
  File "C:\Users\tarko\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\engine\engine.py", line 58, in render
    done_callback(self)
  File "C:\Users\tarko\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\engine\nodes\pipeline_nodes.py", line 230, in on_done
    group_outputs = node_executor.execute(scene.dream_textures_render_engine.node_tree, depsgraph, node_begin=node_begin, node_update=node_update, node_end=node_end, test_break=self.test_break)
  File "C:\Users\tarko\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\engine\node_executor.py", line 54, in execute
    result = future.result()
  File "C:\Users\tarko\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\generator_process\future.py", line 44, in result
    result = execute_node(node, NodeExecutionContext(depsgraph, node_update, test_break), cache)
  File "C:\Users\tarko\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\engine\node_executor.py", line 37, in execute_node
    raise self._exception
FileNotFoundError: [Errno 2] The system cannot find the path specified: 'C:\\Users\\tarko/.cache\\huggingface\\diffusers\\refs'
    result = node.execute(context, **kwargs)
  File "C:\Users\tarko\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\engine\nodes\pipeline_nodes.py", line 243, in execute
    raise exception
  File "C:\Users\tarko\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\generator_process\future.py", line 100, in run_callbacks
    done_callback(self)
  File "C:\Users\tarko\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\engine\nodes\pipeline_nodes.py", line 230, in on_done
    result = future.result()
  File "C:\Users\tarko\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\generator_process\future.py", line 44, in result
    raise self._exception
FileNotFoundError: [Errno 2] The system cannot find the path specified: 'C:\\Users\\tarko/.cache\\huggingface\\diffusers\\refs'
Error: [Errno 2] The system cannot find the path specified: 'C:\\Users\\tarko/.cache\\huggingface\\diffusers\\refs'

### Environment

- Blender version 3.5.1
- AI Render version 0.7.8
- Operating system Win 11

### Screenshots/video

<img width="411" alt="image" src="https://user-images.githubusercontent.com/131181237/235137260-e14543e6-76a5-4d3f-9be8-b570ef897161.png">
<img width="465" alt="image" src="https://user-images.githubusercontent.com/131181237/235137341-b3ee5029-cb08-4442-8233-452013a7062b.png">

**Comment by benrugg** [comment]
The error you're getting is actually from a different add-on (Dream Textures - https://github.com/carson-katri/dream-textures)

Looks like maybe you have both that and AI Render installed.
